### ISSUE TITLE
Extend another service groups

### ISSUE THREAD

**Issue by esloch** [sugar-org/sugar#23]
* containers-sugar version:
* Python version:
* Operating System:

#### Popose:
Use base images created in advance.

**Comment by xmnlab** [comment]
# example

Consider the following .sugar.yaml:

```yaml

version: 1.0
compose-app: docker compose
env-file: .env
defaults:
  group: {{ env.KXGR_GROUP }}
  project-name: sugar-{{ env.KXGR_PROJECT_NAME }}
groups:
  dev:
    project-name: dev
    compose-path: 
      - tests/containers/compose.dev.yaml
    env-file: .env
    services:
      default: django,prostgresql
      available:
        - name: django
        - name: postgresql
        - name: service1-3

  staging:
    project-name: staging
    compose-path: 
      - tests/containers/compose-staging.yaml
    env-file: .env
    services:
      default: django,nginx,postgresql
      available:
        - name: django
        - name: nginx
        - name: postgresql

  prod:
    project-name: prod
    compose-path:
      - tests/containers/compose-prod.yaml
    env-file: .env
    services:
      default: django,nginx,postgresql
      available:
        - name: django
        - name: nginx
        - name: postgresql
        - name: memcache
````


it would be nice to have a mechanism for extend other groups.



```yaml

version: 1.0
compose-app: docker compose
env-file: .env
defaults:
  group: {{ env.KXGR_GROUP }}
  project-name: sugar-{{ env.KXGR_PROJECT_NAME }}
groups:
  base:
    compose-path: 
      - tests/containers/compose.dev.yaml
    env-file: .env
    services:
      default: django,prostgresql
      available:
        - name: django
        - name: postgresql

  dev:
    compose-path: 
      - tests/containers/compose.dev.yaml
    extends: base

  staging:
    compose-path: 
      - tests/containers/compose-staging.yaml
    extends: base
    services:
      default: nginx
      available:
        - name: nginx

  prod:
    compose-path:
      - tests/containers/compose-prod.yaml
    extends: base
    services:
      default: nginx,memcache
      available:
        - name: nginx
        - name: memcache
````
