### ISSUE TITLE
Create a mechanism for overriding resulting config

### ISSUE THREAD

**Issue by xmnlab** [sugar-org/sugar#41]
Proposal:

```yaml

backend: compose
profiles:
  profile1:
    config-path:
      - containers/tests/profile1/compose.yaml
    overrides:
      services:
        web:
          ports:
            - "80:8000"
```

**Comment by frhanjav** [comment]
### Things to consider:

1. Adding networks to sugar:
  - Similar to docker compose, we allow users to define networks in the `.sugar.yaml` file and assign them to specific groups and services.

the structure of the `.sugar.yaml` would look something like this :

```yaml
networks:  
  custom_network1:
    driver: bridge
    driver_opts: ..xyz
  custom_network2:
    driver: overlay  # For future swarm integration
```

2. Future Integration with docker swarm:
- Since we're also working on adding `swarm` support, we need to keep in mind that swarm automatically manages networking via overlay networks.
- Instead of manually defining networks in swarm mode, sugar could auto-generate overlay networks for groups/profiles.

3. Expanding sugar for swarm:

  As mentioned by a previous contributor on the config reloading issue (https://github.com/osl-incubator/sugar/issues/63#issuecomment-2718670072), docker secrets and configs are primarily available for swarm services. After further brainstorming, I realized that we could also leverage multi-host networking (https://docs.docker.com/compose/how-tos/networking/#multi-host-networking) to enhance container communication across nodes.
  
  Additionally, adopting a swarm-first approach, where even standalone containers run as a service with a scale of 1, would simplify network management by keeping everything under swarm’s built-in orchestration. This ensures a more consistent and uniform networking model.
  
  Moreover, while Raft is not directly responsible for container networking, it plays a crucial role in cluster-wide decisions, including managing swarm services and networking configurations. This means that the networking setup itself can benefit from swarm’s built-in orchestration capabilities, improving reliability and scalability.

### Goals
- Short-Term: Implement network support in `.sugar.yaml` for Docker Compose
- Long-Term: Extend sugar’s backend to wrap docker swarm

excited to work on this issue and bring these improvements to sugar :D
